language: python
env:
  - ETCD_ADDR="127.0.0.1"
  - ETCD_PORT_1=2379
  - ETCD_PORT_2=2380
services:
  - docker
# run py38 and lint as separate CI processes
matrix:
  include:
    - python: 3.8
      dist: xenial
      env: TOXENV=py38
    - python: 3.8
      dist: xenial
      env: TOXENV=lint

# install tox, codecov and mosquitto
install:
  - pip install --upgrade pip
  - pip install codecov tox
  - docker pull toke/mosquitto
  - docker pull quay.io/coreos/etcd
# command to run tests
script:
  # run mosquitto container
  - >
    docker run
    --name=mosquittoc
    --publish 1883:1883
    --network=host
    toke/mosquitto
  # run ETCD container
  - >
    docker run
    --name=etcdc
    --network=host
    quay.io/coreos/etcd
    /usr/local/bin/etcd
    --data-dir=/etcd-data --name etcd_node
    --initial-advertise-peer-urls http://${ETCD_ADDR}:${ETCD_PORT_2} --listen-peer-urls http://0.0.0.0:${ETCD_PORT_2}
    --advertise-client-urls http://${ETCD_ADDR}:${ETCD_PORT_1} --listen-client-urls http://0.0.0.0:${ETCD_PORT_1}
    --initial-cluster etcd_node=http://${ETCD_ADDR}:${ETCD_PORT_2}
  - tox
# upload coverage report to Codecov
after_script:
  - codecov --token=c50e2e84-7c1e-4fca-be9c-0528adcac0ed
