language: python

# run py38 and lint as separate CI processes
matrix:
  include:
    - python: 3.8
      dist: xenial
      env: TOXENV=py38
    - python: 3.8
      dist: xenial
      env: TOXENV=lint

# install tox
install:
  - pip install --upgrade pip
  - pip install codecov tox
# command to run tests
script:
  - tox
# upload coverage report to Codecov
after_script:
  - codecov --token=c50e2e84-7c1e-4fca-be9c-0528adcac0ed
